### ISSUE TITLE
manage.py

### ISSUE THREAD

**Issue by sujeetmishra113** [sanikamal/django-chatbot#2]
manage.py missing pls upload it

**Comment by sanikamal** [comment]
manage.py file is not missing.
I am just uploading the app.

First, you have to create django project.
 `django-admin startproject mysite` 
Above command will create a django project mysite
then paste the sili app inside mysite

**Comment by sanikamal** [comment]
Don't forget to add the app in settings.py

Also config the URL of the app in project-specific urls.py file.
